### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by domitix** [andresquintanilla/fitbit-activity-recognition#1]
Hi, I'm interested in your project and I would like to know how to run it. Thank you in advance.

**Comment by andresquintanilla** [comment]
Hi, thanks for reaching out. If this is your first time ever creating a Fitbit application, I'd strongly recommend you to read the [Fitbit Developer Guide](https://dev.fitbit.com/getting-started/). 

A couple things to notice: this app was developed for the Fitbit Versa device only (might not work for the Ionic, Versa Lite or Versa 2). Also, you would need an actual Fitbit OS Device and activate the "Developer Bridge" on your device to run the app; the Fitbit OS Simulator does not handle accelerometer or gyroscope readings, so this particular app would not work on the simulator.

Finally, the predicting model for the activity recognition is still on development and is a separate project from this app, in the meantime you will need to provide your own web service for inference scoring and use it in the fetch logic on the next file **./common/utilsCompanion.js**

I recently updated the README file, I'll try to add more details and requirements over the next few days.

Let me know if you have other questions.
